# Generated by Django 2.2 on 2019-04-13 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=6, null=True)),
                ('contact_no', models.CharField(help_text='98XXXXXXXX', max_length=15, null=True, unique=True, validators=[users.models.validate_mobile_no_is_numeric], verbose_name='Mobile No')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(choices=[('GR', 'Graduation'), ('PG', 'Post Graduation'), ('VO', 'Vocational'), ('HS', 'Higher Secondary'), ('SE', 'Secondary'), ('EL', 'Elementary'), ('NO', 'None')], default='NO', max_length=8, null=True)),
                ('occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
