# Generated by Django 2.2 on 2019-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='content',
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_des',
            field=models.TextField(null=True),
        ),
    ]
