# Generated by Django 2.2 on 2019-04-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190424_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='preference',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AddField(
            model_name='complaints',
            name='solved',
            field=models.CharField(choices=[('SOLVED', 'solved'), ('NOT SOLVED', 'unsolved'), ('UNDER CONSIDERATION', 'under consideration')], default='NOT SOLVED', max_length=50),
        ),
    ]
